config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get '/about' => 'homes#about'
  get '/sign_up' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, except: [:new]
  resources :products do
    resources :feedbacks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show], param: :word
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :products, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  # 画像が存在しない場合にデフォルト画像をActiveStorageに格納する&サイズ調整。
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_user_image.jpeg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @products = Product.where(user_id: @user.id)
    # @userがいいねしたproductのidを配列でfavoritesに保存
    favorites = Favorite.where(user_id: @user.id).pluck(:product_id)
    @favorites_products = Product.find(favorites)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the ShareBack!"
      log_in(@user)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィール情報を更新しました!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

    def destroy
      @user = User.find(params[:id])
      if @user.destroy
        flash[:success] = "アカウントを削除しました"
        redirect_to root_path
      else
        render :edit
      end
    end


  private

    def user_params
      params.require(:user).permit(:name, :email, :introduction, :password, :password_confirmation, :image)
    end

    # @userがカレントユーザーであればtrueを返す
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="ui container">
  <h2>ユーザー情報編集</h2>

  <div class="ui large form error">
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_messages', object: @user %>

        <div class="field">
          <label>画像</label>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="field">
          <label>名前</label>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <label>メールアドレス</label>
          <%= f.email_field :email %>
        </div>

        <div class="field">
          <label>自己紹介</label>
          <%= f.text_area :introduction %>
        </div>

        <h3>パスワード変更（変更なしの場合は空欄のまま）</h3>
        <div class="field">
          <label>パスワード</label>
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <label>パスワード再入力</label>
          <%= f.password_field :password_confirmation %>
        </div>

        <div class="ui left icon input">
          <i class="save icon"></i>
          <%= f.submit '編集内容を保存', class: "ui green button" %>
        </div>
      <% end %>
  </div>

  <div class="ui hidden divider">
    <%= link_to user_path(@user), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "ui red button" do %>
      <i class="trash icon"></i>
      アカウントを削除する
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="ui container">
  <h2>ユーザー一覧</h2>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>ID</th>
        <th>名前</th>
        <th>メールアドレス</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td data-label="ID"><%= user.id %></td>
        <td data-label="名前"><%= link_to user.name, user_path(user) %></td>
        <td data-label="メールアドレス"><%= user.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="ui container">
  <h2>新規登録</h2>
  <div class="ui large form error">
    <div class="ui stacked segment">
      <%= form_with model: @user do |f| %>
        <%= render 'shared/error_messages', object: @user %>

        <div class="field">
          <label>名前</label>
          <div class="ui left icon input">
            <i class="user icon"></i>
            <%= f.text_field :name, placeholder: "例：サンプル太郎" %>
          </div>
        </div>

        <div class="field">
          <label>メールアドレス</label>
          <div class="ui left icon input">
            <i class="envelope icon"></i>
            <%= f.email_field :email, placeholder: "例：example@gmail.com" %>
            </div>
        </div>

        <div class="field">
          <label>パスワード</label>
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <%= f.password_field :password, placeholder: "例：●●●●●●(6文字以上)" %>
          </div>
        </div>

        <div class="field">
          <label>パスワード再入力</label>
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <%= f.password_field :password_confirmation, placeholder: "例：●●●●●●(6文字以上)" %>
            </div>
        </div>

        <%= f.submit '新規登録', class: "ui fluid large teal button" %>
      <% end %>
    </div>
  </div>
  <div class="ui message">
    <p>登録済みの方→ <%= link_to "ログイン", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="ui container">
  <% if @user == current_user %>
    <h1 class="heading">マイページ</h1>
  <% else %>
    <h1 class="heading">ユーザー情報</h1>
  <% end %>

  <div class="ui two column stackable grid">
    <!--左側-->
    <div class="five wide column">
      <div class="ui segment center aligned">
        <div class="ui tiny image">
          <%= image_tag @user.get_image(100,100) %>
        </div>
        <div class="content">
          <p class="header"><%= @user.name %></p>
          <p class="meta"><%= @user.email %></p>
        </div>
        <div class="ui divider"></div>
        <!--メニュータブ-->
        <div class="ui vertical menu" style="margin: auto; max-width: 100%">
          <a class="active item" data-tab="profile">プロフィール</a>
          <a class="item" data-tab="products">成果物</a>
          <% if current_user?(@user) %>
            <a class="item" data-tab="favorites">お気に入り</a>
            <%= link_to "ログアウト", logout_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "item" %>
          <% end %>
        </div>
      </div>
    </div>

    <!--右側-->
    <div class="eleven wide column">
      <!--プロフィール-->
      <div class="ui active tab segment" data-tab="profile">
        <div class="ui dividing medium header">プロフィール
          <% if current_user?(@user) %>
            <div class="ui right floated sub header">
              <%= link_to '編集する', edit_user_path(@user) %>
            </div>
          <% end %>
        </div>
        <div class="ui two column grid">
          <div class="five wide column">名前</div>
          <div class="eleven wide column"><%= @user.name %></div>
          <div class="five wide column">メールアドレス</div>
          <div class="eleven wide column"><%= @user.email %></div>
          <div class="five wide column">自己紹介</div>
          <div class="eleven wide column"><%= @user.introduction %></div>
        </div>
      </div>

    <!--成果物-->
      <div class="ui tab segment" data-tab="products" style="margin: auto">
        <div class="ui dividing medium header">成果物</div>
          <div class="ui link cards two column stackable grid">
            <% @products.each do |product| %>
            <div class="column">
              <div class="ui fluid card">
                <div class="image">
                  <%= link_to product_path(product) do %>
                      <%= image_tag product.get_image(1000,1000), class: "img_status" %>
                  <% end %>
                </div>
                <div class="content">
                  <div class="ui dividing header"><%= link_to product.title, product_path(product) %>
                    <span id="favorite_btn_<%= product.id %>" class="ui right floated sub header" style="padding-top: 2.1px;">
                      <%= render partial: 'favorites/favorite_btn', locals: { product: product } %>
                    </span>
                    <div class="sub header"><%= link_to product.user.name, user_path(product.user), style: "color: gray;" %></div>
                  </div>
                  <div class="description"><%= product.overview %></div>
                </div>
                <div class="extra content">
                  <div class="ui blue mini labels">
                    <% product.tags.each do |tag| %>
                      <%= link_to tag.name, tag_path(tag.url_word), class: "ui blue basic mini label" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
      </div>

      <!--お気に入り-->
      <% if current_user?(@user) %>
        <div class="ui tab segment" data-tab="favorites" style="margin: auto">
          <div class="ui dividing medium header">お気に入り</div>
          <div class="ui link cards two column stackable grid">
              <% @favorites_products.each do |product| %>
              <div class="column">
                <div class="ui fluid card">
                  <div class="image">
                    <%= link_to product_path(product) do %>
                        <%= image_tag product.get_image(1000,1000), class: "img_status" %>
                    <% end %>
                  </div>
                  <div class="content">
                    <div class="ui dividing header"><%= link_to product.title, product_path(product) %>
                      <span id="favorite_btn_<%= product.id %>" class="ui right floated sub header" style="padding-top: 2.1px;">
                        <%= render partial: 'favorites/favorite_btn', locals: { product: product } %>
                      </span>
                      <div class="sub header"><%= link_to product.user.name, user_path(product.user), style: "color: gray;" %></div>
                    </div>
                    <div class="description"><%= product.overview %></div>
                  </div>
                  <div class="extra content">
                    <div class="ui blue mini labels">
                      <% product.tags.each do |tag| %>
                        <%= link_to tag.name, tag_path(tag.url_word), class: "ui blue basic mini label" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>

  </div>
</div>