config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get '/about' => 'homes#about'
  get '/sign_up' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, except: [:new]
  resources :products do
    resources :feedbacks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show], param: :word
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :good_point,  presence: true
  validates :improvement_point, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @product = Product.find(params[:product_id])
    @feedbacks = @product.feedbacks
    @product_feedback = Feedback.new(feedback_params)
    @product_feedback.user_id = current_user.id
    @product_feedback.product_id = @product.id
    unless @product_feedback.save
      render "error" # feedbacks/error.js.erb
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @feedbacks = @product.feedbacks
    Feedback.find(params[:id]).destroy
  end

  private
    def feedback_params
      params.require(:feedback).permit(:good_point, :improvement_point, :other)
    end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_index.html.erb
<% feedbacks.each do |feedback| %>
  <div class="ui piled segment">
    <div class="ui feed">
      <div class="event">
        <div class="label">
          <%= image_tag feedback.user.get_image(50,50), class: "img_status" %>
        </div>
        <div class="content">
          <div class="date"><%= l feedback.created_at %></div>
          <div class="summary">
            <%= link_to feedback.user.name, user_path(feedback.user) %>
          </div>
        </div>
        <% if feedback.user == current_user %>
          <div class="ui right aligned">
            <%= link_to product_feedback_path(feedback.product,feedback), method: :delete, data: {confirm: "フィードバックを削除しますか？"}, remote: true do %>
              <button class="ui icon inverted red button"><i class="trash alternate icon"></i></button>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="ui header">良かった点</div>
      <p><%= feedback.good_point %></p>
    <h3 class="ui header">改善点</h3>
      <p><%= feedback.improvement_point %></p>
    <% if feedback.other? %>
      <h3 class="ui header">その他</h3>
        <p><%= feedback.other %></p>
    <% end %>
  </div>
<% end %>

app/views/feedbacks/create.js.erb
$(".feedback").html("<%= j(render partial: 'feedbacks/index', locals: {feedbacks: @feedbacks, object: @product_feedback}) %>");

<!--投稿後はフォームを空にする-->
$(".good_point").val("");
$(".improvement_point").val("");
$(".feedback_other").val("");

<!--投稿失敗→投稿成功時にエラーメッセージを消す-->
$(".feedback_error").empty();
<!--投稿できたら.feedbacks_emptyのメッセージを消す-->
$(".feedbacks_empty").empty();

app/views/feedbacks/destroy.js.erb
$(".feedback").html("<%= j(render partial: 'feedbacks/index', locals: {feedbacks: @feedbacks}) %>");

<!--フィードバックが無い場合(全て削除された場合)に説明を入れる-->
<% if @feedbacks.empty? %>
  $(".feedbacks_empty").text("この投稿にまだフィードバックはありません。");
<% end %>

app/views/feedbacks/edit.html.erb
<h1>feedback#edit</h1>

app/views/feedbacks/error.js.erb
$(".feedback_error").html("<%= j(render partial: 'shared/error_messages', locals: {object: @product_feedback}) %>");