config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get '/about' => 'homes#about'
  get '/sign_up' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, except: [:new]
  resources :products do
    resources :feedbacks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show], param: :word
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :feedbacks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  has_one_attached :image, dependent: :destroy
  MAX_TAGS_COUNT = 5

  with_options presence: true do
  validates :title
  validates :url
  validates :overview
  validates :background
  validates :usage
  validates :ingenuity
  validates :features
  validates :technology
  end
  validates :overview, length: { maximum: 50 }

  # 画像が存在しない場合にデフォルト画像をActiveStorageに格納する&サイズ調整。
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_app_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # いいねしているかどうか
  def favorited_by?(user)
    if !user
      return false
    end
    favorites.exists?(user_id: user.id)
  end

  # url用に文字列を生成する
  def create_url_word(tag_name)
    if tag_name.index('.')
      tag_name = tag_name.gsub('.','-')
    end
    tag_name = tag_name.downcase
  end

  #タグ機能
  def save_tags(sent_tags)
    # すでに付与されているタグを取得
    current_tags = self.tags.pluck(:name)
    # 付与されているタグから送信されたタグを除いたものをoldとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから付与されているタグを除いたものをnewとする
    new_tags = sent_tags - current_tags
    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
      # 使われていないタグは削除する
      if Tag.find_by(name: old).products.empty?
        Tag.find_by(name: old).destroy
      end
    end
    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new, url_word: create_url_word(new))
      self.tags << new_post_tag
    end
  end

  #タグ数の上限を設定
  def max_tags(tags_count)
    if tags_count > MAX_TAGS_COUNT
      self.errors.add(:base, "タグは#{MAX_TAGS_COUNT}つ以内で指定してください")
      return false
    else
      return true
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find(params[:id])
    @product_feedback = Feedback.new
    @feedbacks = @product.feedbacks
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    tag_list = params[:product][:tag_names].delete(' ').delete('　').split(',')
    if @product.max_tags(tag_list.count) && @product.save
      flash[:success] = "投稿しました！"
      @product.save_tags(tag_list)
      redirect_to product_path(@product)
    else
      @tag_list = tag_list.join(', ')
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @tag_list = @product.tags.pluck(:name).join(', ')
  end

  def update
    @product = Product.find(params[:id])
    tag_list = params[:product][:tag_names].delete(' ').delete('　').split(',')
    if @product.update(product_params) && @product.max_tags(tag_list.count)
      flash[:success] = "変更を保存しました！"
      @product.save_tags(tag_list)
      redirect_to product_path(@product)
    else
      @tag_list = tag_list.join(', ')
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "削除しました！"
      redirect_to products_path
    else
      render :edit
    end
  end

  private

    def product_params
      params.require(:product).permit(:user_id, :title, :url, :overview, :background, :usage, :ingenuity, :other, :features, :technology, :image)
    end

    # beforeアクション
    # userがカレントユーザーであればtrueを返す
    def correct_user
      product = Product.find(params[:id])
      user = product.user
      unless current_user?(user)
        redirect_to root_path
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="ui container">
  <h2 class="heading">成果物編集</h2>
  <div class="ui large form error">
    <%= form_with model: @product do |f| %>
      <%= render 'shared/error_messages', object: @product %>
      <div class="field">
        <label>画像（aboutページ、topページ、ロゴなど）</label>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="ui yellow tiny message">
        <div class="header">画像には比率が「3:2」のものを使用してください</div>
        <ul class="list">
          <li>「960x640」「1200x800」「2400x1600」などが推奨です。</li>
          <li>「3:2」のサイズ一覧は<%= link_to "こちら", 'https://blog.phantom4.org/archives/300', target: :_blank, rel: "noopener noreferrer" %></li>
        </ul>
      </div>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :url %>
        <%= f.text_field :url %>
      </div>
      <div class="field">
        <%= f.label :tag_names %>
        <%= f.text_field :tag_names, value: @tag_list, placeholder: "成果物に関連するタグをカンマ区切りで5つまで入力。（例：Ruby,Rails）" %>
      </div>
      <div class="field">
        <%= f.label :overview %>
        <%= f.text_field :overview %>
      </div>
      <div class="field">
        <%= f.label :background %>
        <%= f.text_area :background %>
      </div>
      <div class="field">
        <%= f.label :usage %>
        <%= f.text_area :usage %>
      </div>
      <div class="field">
        <%= f.label :ingenuity %>
        <%= f.text_area :ingenuity %>
      </div>
      <div class="field">
        <%= f.label :other %>
        <%= f.text_area :other %>
      </div>
      <div class="field">
        <%= f.label :features %>
        <%= f.text_area :features %>
      </div>
      <div class="field">
        <%= f.label :technology %>
        <%= f.text_area :technology %>
      </div>
      <div class="ui left icon input">
        <i class="save icon"></i>
        <%= f.submit '変更内容を保存する', class: "ui green button " %>
      </div>

      <%= link_to product_path(@product), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "ui right floated red button" do %>
        <i class="trash icon"></i>
        成果物を削除する
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="ui container">
  <h2 class="heading">成果物一覧</h2>
  <div class="ui link cards three column stackable grid">
    <% @products.each do |product| %>
    <div class="column">
      <div class="ui fluid card">
        <div class="image">
          <%= link_to product_path(product) do %>
              <%= image_tag product.get_image(1000,1000), class: "img_status" %>
          <% end %>
        </div>
        <div class="content">
          <div class="ui dividing header"><%= link_to product.title, product_path(product) %>
            <span id="favorite_btn_<%= product.id %>" class="ui right floated sub header" style="padding-top: 2.1px;">
              <%= render partial: 'favorites/favorite_btn', locals: { product: product } %>
            </span>
            <div class="sub header"><%= link_to product.user.name, user_path(product.user), style: "color: gray;" %></div>
          </div>
          <div class="description"><%= product.overview %></div>
        </div>
        <div class="extra content">
          <div class="ui blue mini labels">
            <% product.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag.url_word), class: "ui blue basic mini label" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/products/new.html.erb
<div class="ui container">
  <h2 class="heading">成果物投稿</h2>
  <div class="ui large form error">
    <%= form_with model: @product do |f| %>
      <%= render 'shared/error_messages', object: @product %>
      <div class="field">
        <label>画像（aboutページ、topページ、ロゴなど）</label>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="ui yellow tiny message">
        <div class="header">画像には比率が「3:2」のものを使用してください</div>
        <ul class="list">
          <li>「960x640」「1200x800」「2400x1600」などが推奨です。</li>
          <li>「3:2」のサイズ一覧は<%= link_to "こちら", 'https://blog.phantom4.org/archives/300', target: :_blank, rel: "noopener noreferrer" %></li>
        </ul>
      </div>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :url %>
        <%= f.text_field :url %>
      </div>
      <div class="field">
        <%= f.label :tag_names %>
        <%= f.text_field :tag_names, value: @tag_list, placeholder: "成果物に関連するタグをカンマ区切りで5つまで入力。（例：Ruby,Rails）" %>
      </div>
      <div class="field">
        <%= f.label :overview %>
        <%= f.text_field :overview %>
      </div>
      <div class="field">
        <%= f.label :background %>
        <%= f.text_area :background %>
      </div>
      <div class="field">
        <%= f.label :usage %>
        <%= f.text_area :usage %>
      </div>
      <div class="field">
        <%= f.label :ingenuity %>
        <%= f.text_area :ingenuity %>
      </div>
      <div class="field">
        <%= f.label :other %>
        <%= f.text_area :other %>
      </div>
      <div class="field">
        <%= f.label :features %>
        <%= f.text_area :features %>
      </div>
      <div class="field">
        <%= f.label :technology %>
        <%= f.text_area :technology %>
      </div>
      <%= f.submit '投稿する', class: "ui blue button" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="ui container">
  <div class="ui items">
    <div class="item">
      <%= link_to user_path(@product.user), class: "ui image" do %>
        <%= image_tag @product.user.get_image(80,80), class: "img_status" %>
      <% end %>
      <div class="middle aligned content">
        <%= link_to @product.user.name, user_path(@product.user) %>
        <div class="description">
          <p>投稿日: <%= l @product.created_at %></p>
          <p>更新日: <%= l @product.updated_at %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui center aligned grid">
    <%= image_tag @product.get_image(2000,2000), class: "thirteen wide column img_status" %>
  </div>

  <div class="ui grid">
    <div class="ui blue labels">
      <% @product.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag.url_word), class: "ui blue basic label" %>
      <% end %>
    </div>
  </div>

  <!--タブ機能-->
  <div class="ui two item menu">
    <a class="active item" data-tab="product_show">成果物詳細</a>
    <a class="item" data-tab="feedbacks">フィードバック</a>
  </div>
  <!--タブ（成果物詳細）-->
  <div class="ui active tab segment" data-tab="product_show">
    <h2 class="ui dividing header"><%= @product.title %>
      <!--自分のだったら編集ボタン出す-->
      <% if current_user?(@product.user) %>
        <div class="ui right floated sub header">
          <p><%= link_to '編集する', edit_product_path(@product) %></p>
        </div>
      <% end %>
      <!--いいねボタン-->
      <span id="favorite_btn_<%= @product.id %>" class="ui right floated sub header" style="padding-top: 2.1px;">
        <%= render partial: 'favorites/favorite_btn', locals: { product: @product } %>
      </span>

      <div class="sub header"><%= link_to @product.url, @product.url, target: "_blank", rel: "noopener noreferrer" %></div>
    </h2>

    <p><%= safe_join(@product.overview.split("\n"),tag(:br)) %></p>

    <div class="ui dividing large header">
      <i class="comment outline icon"></i>
      <div class="content">作成背景</div>
    </div>
    <p><%= safe_join(@product.background.split("\n"),tag(:br)) %></p>

    <div class="ui dividing large header">
      <i class="thumbtack icon"></i>
      <div class="content">使い方</div>
    </div>
    <p><%= safe_join(@product.usage.split("\n"),tag(:br)) %></p>

    <div class="ui dividing large header">
      <i class="lightbulb outline icon"></i>
      <div class="content">工夫点</div>
    </div>
    <p><%= safe_join(@product.ingenuity.split("\n"),tag(:br)) %></p>

    <div class="ui dividing large header">
      <i class="pencil alternate icon"></i>
      <div class="content">機能一覧</div>
    </div>
    <p><%= safe_join(@product.features.split("\n"),tag(:br)) %></p>

    <div class="ui dividing large header">
      <i class="code icon"></i>
      <div class="content">使用技術</div>
    </div>
    <p><%= safe_join(@product.technology.split("\n"),tag(:br)) %></p>

    <% if @product.other? %>
      <div class="ui dividing large header">
        <i class="info circle icon"></i>
        <div class="content">その他</div>
      </div>
      <p><%= safe_join(@product.other.split("\n"),tag(:br)) %></p>
    <% end %>
  </div>
  <!--タブ（フィードバック）-->
  <div class="ui tab segment" data-tab="feedbacks">
    <% if @feedbacks.empty? %>
      <span class="feedbacks_empty">この投稿にまだフィードバックはありません。</span>
    <% end %>
    <div class="feedback">
      <%= render partial: 'feedbacks/index', locals: {feedbacks: @feedbacks} %>
    </div>

    <!--フィードバックフォーム-->
    <h3>フィードバックを送る</h3>
    <div class="ui large form error">
      <%= form_with model: [@product,@product_feedback], local: false do |f| %>
        <div class="feedback_error">
          <%= render 'shared/error_messages', object: @product_feedback %>
        </div>
        <div class="field">
          <%= f.label :good_point %>
          <%= f.text_area :good_point, rows: 7, class: "good_point" %>
        </div>
        <div class="field">
          <%= f.label :improvement_point %>
          <%= f.text_area :improvement_point, rows: 7, class: "improvement_point" %>
        </div>
        <div class="field">
          <%= f.label :other %>
          <%= f.text_area :other, rows: 2, class: "feedback_other" %>
        </div>

        <button class="ui labeled icon blue button">
          <i class="paper plane icon"></i>
          <%= f.submit '送信', class: "submit" %>
        </button>
      <% end %>
    </div>
  </div>
  <!--↑タブ機能おわり-->

</div>