config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get '/about' => 'homes#about'
  get '/sign_up' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, except: [:new]
  resources :products do
    resources :feedbacks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :tags, only: [:index, :show], param: :word
end

app/views/layouts/_header.html.erb
<header class="ui menu">
<% if logged_in? %>
  <%= link_to "ShareBack", root_path, class: "item" %>
  <%= link_to "タグから探す", tags_path, class: "item" %>
  <div class="right menu">
    <%= link_to "マイページ", user_path(current_user), class: "item" %>
    <div class="item">
      <%= link_to "新規投稿", new_product_path, class: "ui button" %>
    </div>
  </div>
<% else %>
  <%= link_to "ShareBack", root_path, class: "item" %>
  <%= link_to "ShareBackとは？", about_path, class: "item" %>
  <%= link_to "タグから探す", tags_path, class: "item" %>
  <div class="right menu">
    <div class="item">
      <%= link_to "新規登録", sign_up_path, class: "ui button primary" %>
    </div>
    <div class="item">
      <%= link_to "ログイン", login_path, class: "ui button primary" %>
    </div>
    <div class="item">
      <%= link_to "新規投稿", new_product_path, class: "ui button" %>
    </div>
  </div>
<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareBack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--↓Semantic UIを動かす用のjsファイル-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>

    <div>
      <% flash.each do |message_type, message| %>
        <div class="ui <%= message_type %> message">
          <%= message %>
        </div>
      <% end %>
    </div>

    <%= yield %>
    <footer></footer>
  </body>
</html>